// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcvstjdkqacuqhvbdvis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jdnN0amRrcWFjdXFodmJkdmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTYwMjYsImV4cCI6MjA2MTc3MjAyNn0.swxshdjpZFKDs__C9g9-9mFauDZWJcjoQwFkNm1U9GM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);